### ISSUE TITLE
Layer trashcan crashes if there are no layers

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#126]
Trying to delete a layer when there isn't one causes a crash.
```
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/specviz/build/lib.macosx-10.5-x86_64-3.5/specviz/ui/controller.py", line 76, in <lambda>
    lambda: layer_manager.remove(self.viewer.current_layer))
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/specviz/build/lib.macosx-10.5-x86_64-3.5/specviz/interfaces/managers.py", line 114, in remove
    self._members.remove(layer)
ValueError: list.remove(x): x not in list
Abort trap: 6
(specviz_env)Henrys-MacBook-Pro:specview hcferguson$ specviz
WARNING:root:No such event: on_remove_plot. Event must be registered before listeners can be assigned.
WARNING:root:No such event: on_remove_plot. Event must be registered before listeners can be assigned.
WARNING:root:No such event: on_remove_plot.
Segmentation fault: 11
(specviz_env)Henrys-MacBook-Pro:specview hcferguson$ specviz
WARNING:root:No such event: on_remove_plot. Event must be registered before listeners can be assigned.
WARNING:root:No such event: on_remove_plot. Event must be registered before listeners can be assigned.
WARNING:root:No such event: on_remove_plot.
WARNING:root:No such event: on_remove_plot.
WARNING:root:No such event: on_remove_plot. Event must be registered before listeners can be assigned.
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/specviz/build/lib.macosx-10.5-x86_64-3.5/specviz/ui/controller.py", line 76, in <lambda>
    lambda: layer_manager.remove(self.viewer.current_layer))
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/specviz/build/lib.macosx-10.5-x86_64-3.5/specviz/interfaces/managers.py", line 114, in remove
    self._members.remove(layer)
ValueError: list.remove(x): x not in list
Abort trap: 6
```

**Comment by nmearl** [comment]
Fixed in #135.
