### ISSUE TITLE
Re-implement third axis

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#13]
Copy over the code for the top axis on the plots with a dialog option for velocity/redshift/index labels.

**Comment by pllim** [comment]
I am getting `RuntimeWarning` after you added the velocity axis. There needs to be a way to handle invalid values during unit conversion (e.g., division by zero).

**Comment by nmearl** [comment]
Can you provide the traceback? What are you doing that invokes this error?

**Comment by pllim** [comment]
You can use any of the files provided by @hcferguson in #46 and use the latest master version to open using
```
pyfocal example_spec_ipac.txt
```
Click the plot button and you will see this
```python
.../astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
```

**Comment by pllim** [comment]
When dispersion unit is not present and unit conversion fails, Pyfocal should handle it more gracefully instead of throwing this error:
```python
Traceback (most recent call last):
  File ".../pyqtgraph/graphicsItems/AxisItem.py", line 525, in paint
    specs = self.generateDrawSpecs(painter)
  File ".../pyqtgraph/graphicsItems/AxisItem.py", line 926, in generateDrawSpecs
    strings = self.tickStrings(values, self.autoSIPrefixScale * self.scale, spacing)
  File ".../Pyfocal-0.1a1-py2.7.egg/pyfocal/ui/widgets/axes.py", line 41, in tickStrings
    c = const.c.to('{}/s'.format(spatial_unit))
  File ".../astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/units/quantity.py", line 634, in to
    equivalencies=equivalencies)
  File ".../astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/units/core.py", line 968, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File ".../astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/units/core.py", line 869, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File ".../astropy-1.1.1-py2.7-linux-x86_64.egg/astropy/units/core.py", line 860, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 'm / s' (speed) and '1 / s' (frequency) are not convertible
```

**Comment by pllim** [comment]
@nmearl , my reported traceback is gone. This issue is done, right?
