### ISSUE TITLE
Crash when deleting a layer

### ISSUE THREAD

**Issue by gderosa2004** [spacetelescope/specviz#152]
I've tried to delete a layer but everything crashed - selected layer, pushed trash button.
`Traceback (most recent call last):
  File "/Users/gderosa/anaconda/envs/sviz_env/lib/python3.5/site-packages/specviz-0.1.0a1.dev253-py3.5.egg/specviz/ui/controller.py", line 437, in remove_layer
    model_manager.remove(layer=current_layer)
  File "/Users/gderosa/anaconda/envs/sviz_env/lib/python3.5/site-packages/specviz-0.1.0a1.dev253-py3.5.egg/specviz/interfaces/managers.py", line 261, in remove
    del self._members[layer]
KeyError: <specviz.core.data.Layer object at 0x1174f6668>
Abort trap: 6
`

**Comment by nmearl** [comment]
This should not be happening. You must be using an old version of the code base. Are you sure you did:

```bash
$ git pull
$ pip install -r requirements.txt
```

**Comment by gderosa2004** [comment]
Yep.. Found out I cloned the wrong directory. -_-
