### ISSUE TITLE
Mask IndexError when fitting a model

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#188]
Follow up of #150, when I actually attempt to fit a model by clicking "Perform Fit". This time using HST/COS data provided by Gisella.

``` python
.../astropy/units/quantity.py:894: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 2746 but corresponding boolean dimension is 9167
  out = super(Quantity, self).__getitem__(key)
Traceback (most recent call last):
  File ".../specviz/ui/controller.py", line 412, in fit_model_layer
    fitter_name=self.viewer.current_fitter)
  File ".../specviz/interfaces/managers.py", line 384, in fit_model
    flux = parent_layer.data[mask]
  File ".../astropy/units/quantity.py", line 894, in __getitem__
    out = super(Quantity, self).__getitem__(key)
IndexError: index 2746 is out of bounds for axis 1 with size 2746
```

**Comment by nmearl** [comment]
Fixed in latest version.
