### ISSUE TITLE
Override units in custom loader

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#219]
The VIPERS project distributed FITS files with the spectra in a FITS binary table, which can be read successfully with Table.read() but which has non-standard units. I created a custom loader, but it fails I think because the fits reader itself rejects the units before specviz can re-interpret them. 

```
In [15]: t = Table.read('VIPERS_110055275_corr.fits')

In [16]: print t
 WAVES        FLUXES         NOISE        SKY        EDIT      MASK
Angstrom erg / (A cm2 s) erg/s/cm^2/Ang  counts erg/s/cm^2/Ang     
-------- --------------- -------------- ------- -------------- ----
 5514.28    -1.28638e-18    1.89357e-18 81.5747    1.64353e-18    1
 5521.42     1.48216e-18    1.60909e-18 94.9008    1.63095e-18    1
```

Here's my custom loader:

```
more ~/.specviz/vipers.yaml
--- !CustomLoader
name: VIPERS
extension: [fits]
wcs:
  hdu: 0
dispersion:
  hdu: 1
  col: 0
  unit: 'Angstrom'
data:
  hdu: 1
  col: 1
  unit: 'erg s-1 cm-2 Angstrom-1'
uncertainty:
  hdu: 1
  col: 2
  type: 'std'
  unit: 'erg s-1 cm-2 Angstrom-1'
meta:
  author: H. Ferguson
```

Here's the traceback:

```
INFO:root:Attempting to open '/Users/hcferguson/Documents/conferences/2016/montreal/presentation/VIPERS/VIPERS_110055275.fits' using filter '<class 'filter'>'.
WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0)
WARNING: UnitsWarning: The unit 'angstrom' has been deprecated in the FITS standard. Suggested: 10**-1 nm. [astropy.units.format.utils]
WARNING:astropy:UnitsWarning: The unit 'angstrom' has been deprecated in the FITS standard. Suggested: 10**-1 nm.
WARNING: UnitsWarning: The unit 'erg' has been deprecated in the FITS standard. Suggested: cm2 g s-2. [astropy.units.format.utils]
WARNING:astropy:UnitsWarning: The unit 'erg' has been deprecated in the FITS standard. Suggested: cm2 g s-2.
WARNING: UnitsWarning: The unit 'G' has been deprecated in the FITS standard. Suggested: 10**-4 T. [astropy.units.format.utils]
WARNING:astropy:UnitsWarning: The unit 'G' has been deprecated in the FITS standard. Suggested: 10**-4 T.
WARNING: UnitsWarning: 'erg/s/cm^2/Ang' did not parse as fits unit: At col 11, Unit 'Ang' not supported by the FITS standard. Did you mean 10**-18 G, 10**-9 G, aG (deprecated), aN, ag, nG (deprecated) or ng? [astropy.units.core]
WARNING:astropy:UnitsWarning: 'erg/s/cm^2/Ang' did not parse as fits unit: At col 11, Unit 'Ang' not supported by the FITS standard. Did you mean 10**-18 G, 10**-9 G, aG (deprecated), aN, ag, nG (deprecated) or ng?
WARNING: UnitsWarning: 'counts' did not parse as fits unit: At col 0, Unit 'counts' not supported by the FITS standard. Did you mean count? [astropy.units.core]
WARNING:astropy:UnitsWarning: 'counts' did not parse as fits unit: At col 0, Unit 'counts' not supported by the FITS standard. Did you mean count?
INFO:root:Dispatch is now watching: <specviz.ui.widgets.sub_windows.PlotSubWindow object at 0x1227b55e8>
ERROR:root:Exception in 'add_plot':
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/core/comms.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/ui/widgets/sub_windows.py", line 263, in add_plot
    new_plot = LinePlot.from_layer(layer)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/core/plots.py", line 67, in from_layer
    plot_container = LinePlot(layer=layer, plot=plot_data_item, **kwargs)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/core/plots.py", line 38, in __init__
    self._layer.unit)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/core/plots.py", line 101, in change_units
    self._layer.set_units(x, y)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/core/data.py", line 151, in set_units
    self.dispersion.data)).value
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/astropy/units/quantity.py", line 653, in to
    equivalencies=equivalencies)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/astropy/units/core.py", line 989, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/astropy/units/core.py", line 1734, in _get_converter
    "to other units.".format(self.name))
ValueError: The unit 'erg/s/cm^2/Ang' is unrecognized.  It can not be converted to other units.
```

**Comment by pllim** [comment]
According to http://specviz.readthedocs.io/en/latest/custom_loaders.html , I must have loaded that unit successfully at one point using `'erg / (Angstrom cm2 s)'`. I think the trick is to get the string in such a way that is recognized by `astropy.unit`.

**Comment by nmearl** [comment]
It seems like at some point, it's looking at the header for the unit information. @hcferguson, is the flux unit described as `erg/s/cm^2/Ang` in the header?

**Comment by pllim** [comment]
Yes, it looks at `TUNITx` first. If not found, then only it reads from YAML.

**Comment by mattjhill** [comment]
So it seems like the loaders should use YAML first if specified since that is what the user is expecting.
