### ISSUE TITLE
Saving model fit to file isn't working 

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#222]
Tried to save a model fit to a file and it didn't work. Here's the traceback.

```
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/plugins/model_fitting_plugin.py", line 477, in save_model
    expression=formula)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/interfaces/model_io/yaml_model_io.py", line 282, in saveModelToFile
    _writeSingleComponentModel(model, model_directory, parent)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/interfaces/model_io/yaml_model_io.py", line 251, in _writeSingleComponentModel
    _writeToFile(out_model_dict, model_directory, parent)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz-0.2.1rc4.dev548-py3.5.egg/specviz/interfaces/model_io/yaml_model_io.py", line 236, in _writeToFile
    f = open(fname, "w")
PermissionError: [Errno 13] Permission denied: '/.yaml'
```

**Comment by nmearl** [comment]
Hmm, I'm not seeing this. The error seems to suggest that you were trying to name your file `/`. The internals will look at the file name and check if it has a `.yaml` suffix, and if not, add it. It seems like you might not have named your file?

**Comment by hcferguson** [comment]
I've tried a bunch of different names and directories and get the same error. I'm using Astroconda with python 3.5.

**Comment by nmearl** [comment]
Are you getting the same exact error in each case?

**Comment by hcferguson** [comment]
Yes.

**Comment by nmearl** [comment]
The other possibility is that when it's retrieving the path from the dialogue box, the `[0]` element on the result is actually the beginning of a string, when it should be the first element of a list.

Are you using the latest `pyqt` from anaconda?

```
$ conda install pyqt
```

**Comment by hcferguson** [comment]
That did the trick.
