### ISSUE TITLE
Support astropy.units.LogUnits in loaders

### ISSUE THREAD

**Issue by mattjhill** [spacetelescope/specviz#249]
I tried to write a loader for an SDSS spectrum ([for example](http://dr12.sdss3.org/spectrumDetail?mjd=52203&fiber=154&plateid=685)).  The files have no WCS info and have a column for loglam, so I tried to use the following loader
```
--- !CustomLoader
name: SDSS Fits
extension: [fits]
wcs:
  hdu: 0
dispersion:
  hdu: 1
  col: 1
  unit: 'dex(Angstrom)'
data:
  hdu: 1
  col: 0
  unit: '1e-17 erg / (Angstrom cm2 s)'
uncertainty:
  hdu: 1
  col: 2
  type: 'ivar'
meta:
  author: STScI
```

This throws an error with the following traceback
```
ERROR:root:Exception in 'add_plot':
Traceback (most recent call last):
  File "/Users/mhill/miniconda3/envs/astroconda/lib/python3.5/site-packages/specviz/core/comms.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "/Users/mhill/miniconda3/envs/astroconda/lib/python3.5/site-packages/specviz/ui/widgets/sub_windows.py", line 278, in add_plot
    new_plot = LinePlot.from_layer(layer)
  File "/Users/mhill/miniconda3/envs/astroconda/lib/python3.5/site-packages/specviz/core/plots.py", line 115, in from_layer
    plot_data_item = pg.PlotDataItem(layer.dispersion, layer.data)
  File "/Users/mhill/miniconda3/envs/astroconda/lib/python3.5/site-packages/specviz/core/data.py", line 156, in dispersion
    Quantity(self._dispersion, unit=self.dispersion_unit),
  File "/Users/mhill/miniconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/quantity.py", line 332, in __new__
    value._set_unit(value_unit)
  File "/Users/mhill/miniconda3/envs/astroconda/lib/python3.5/site-packages/astropy/units/quantity.py", line 722, in _set_unit
    .format(type(self).__name__, UnitBase, type(unit)))
astropy.units.core.UnitTypeError: Quantity instances require <class 'astropy.units.core.UnitBase'> units, not <class 'astropy.units.function.logarithmic.DexUnit'> instances.
```

I'm not sure how much work it would be to make log units compatible but it would be a useful feature.

**Comment by mattjhill** [comment]
I've put a quick fix for the dispersion units in the the loader [here](https://github.com/mattjhill/specviz/commit/4d39e91e7230752a7a34331ad424de23b2a9b174). If you think this is a good way to deal with the log units I can open a PR.

**Comment by weaverba137** [comment]
I am also experiencing this issue.  See also astropy/astropy#5851.

**Comment by nmearl** [comment]
@weaverba137 there is a current fix in the parser for dealing with log units, but you'll have to use the master branch from this repo to gain access. Let me know if you need help with that.

**Comment by weaverba137** [comment]
Thanx, I will give that a try.

**Comment by weaverba137** [comment]
The master branch is working fine on SDSS spectra.  For reference, you might be interested to read the description of SDSS-III/IV spec files: https://data.sdss.org/datamodel/files/BOSS_SPECTRO_REDUX/RUN2D/spectra/PLATE4/spec.html.
