### ISSUE TITLE
Can't get the file open dialog

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#288]
I'm unable to get the file-open dialog. I've updated Astroconda. Tried with the Astroconda specviz and the latest from github with the same error messages....

```
ERROR:root:Exception in 'open_file':
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz/core/comms.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz/plugins/data_list_plugin.py", line 112, in open_file
    file_name, selected_filter = self.open_file_dialog()
  File "/Users/hcferguson/anaconda/envs/astroconda35/lib/python3.5/site-packages/specviz/plugins/data_list_plugin.py", line 139, in open_file_dialog
    initialFilter=self._file_filter)
TypeError: getOpenFileNames(parent: QWidget = None, caption: object = '', directory: object = '', filter: object = '', options: QFileDialog.Options = 0): 'initialFilter' is not a valid keyword argument
```

**Comment by astrofrog** [comment]
Confirmed with PyQt4 (not PyQt5). The solution is to use compatibility functions provided by QtPy, I'll open a PR.
