### ISSUE TITLE
Issue with median line plot

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/specviz#381]
When I select `median` for the line plot it produces an error (`mean` and `sum` work):
```
Traceback (most recent call last):
  File "/Users/crjones/Documents/DATB/cubeviz/specviz/specviz/third_party/glue/data_viewer.py", line 213, in _on_operation_changed
    self._spectrum_from_component(layer, component, wcs, mask=mask)
  File "/Users/crjones/Documents/DATB/cubeviz/specviz/specviz/third_party/glue/data_viewer.py", line 224, in _spectrum_from_component
    spec_data = data.median((1, 2))
  File "/Users/crjones/Documents/DATB/cubeviz/spectral-cube/spectral_cube/spectral_cube.py", line 982, in median
    **kwargs)
  File "/Users/crjones/Documents/DATB/cubeviz/spectral-cube/spectral_cube/spectral_cube.py", line 358, in apply_numpy_function
    **kwargs)
TypeError: `axis` must be an integer or None
```

I'll take a look at this.

**Comment by brechmos-stsci** [comment]
Ah, turns out bottleneck.nanmedian does not allow axis to be a list (ie you can't do something like `output = bnok.nanmedian(data, axis=(1,2))`.  But this is a spectral-cube call issue. Going to post a fix there and close this.
