### ISSUE TITLE
Encoding should be explicitly specified for linelist

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/specviz#408]
It looks like the line list read by specviz contains non-ASCII characters because things don't work if the default encoding is ASCII:

```
$ LC_ALL=C python setup.py --version
INFO:root:Added APOGEE apVisit to loader registry.
INFO:root:Added APOGEE apStar to loader registry.
INFO:root:Added APOGEE aspcapStar to loader registry.
INFO:root:Added Simple Fits to loader registry.
INFO:root:Added HST/COS to loader registry.
INFO:root:Added HST/STIS to loader registry.
INFO:root:Added SDSS-III/IV spec to loader registry.
INFO:root:Added SDSS-I/II spSpec to loader registry.
INFO:root:Added Spectrum ECSV to loader registry.
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    get_debug_option(PACKAGENAME))
  File "/Users/tom/Projects/Glue/STScI/specviz/astropy_helpers/astropy_helpers/setup_helpers.py", line 118, in get_debug_option
    fromlist=['debug'])[0]
  File "/Users/tom/Projects/Glue/STScI/specviz/astropy_helpers/astropy_helpers/version_helpers.py", line 301, in get_pkg_version_module
    mod = __import__(packagename + '.version', fromlist=fromlist)
  File "/Users/tom/Projects/Glue/STScI/specviz/specviz/__init__.py", line 28, in <module>
    linelist.populate_linelists_cache()
  File "/Users/tom/Projects/Glue/STScI/specviz/specviz/core/linelist.py", line 84, in populate_linelists_cache
    linelist = get_from_file(linelist_path, yaml_filename)
  File "/Users/tom/Projects/Glue/STScI/specviz/specviz/core/linelist.py", line 59, in get_from_file
    return LineList.read_list(linelist_fullname, loader)
  File "/Users/tom/Projects/Glue/STScI/specviz/specviz/core/linelist.py", line 226, in read_list
    col_ends = end_list)
  File "/Users/tom/Dropbox/Code/Astropy/astropy/astropy/io/ascii/ui.py", line 327, in read
    table = fileobj.read()
  File "/Users/tom/miniconda3/envs/dev/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 190: ordinal not in range(128)
```

**Comment by kassin** [comment]
@ibusko

**Comment by ibusko** [comment]
I cannot reproduce this error. Indeed, the SDSS line list has species identifiers such as Ly&alpha;. This will choke python code such as 
```
open("SDSS.list").read().encode("ascii")
```
 But it doesn't happen in specviz. Maybe because it uses astropy's ascii reader function (astropy 2.0.3). The line identifiers end up drawn correctly on the display. Could this be related to user-specific environment settings?

**Comment by ibusko** [comment]
The code in specviz works like this:

```
kamino:/Users/busko $ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.io import ascii as A
>>> list = A.read("SDSS.list", format='fixed_width_no_header')
>>> list[0:3]
<Table length=3>
                col1                
               str36                
------------------------------------
1033.82   0.0  1.0  Emission    O VI
 1215.24   0.0  9.0  Emission    Lyα
 1240.81   0.0  3.0  Emission    N V
>>> 
```

**Comment by astrofrog** [comment]
@ibusko - did you try and set ``LC_ALL=C` before running the code? The issue is when explicitly setting the computer locale to C.

**Comment by javerbukh** [comment]
@ibusko @astrofrog should this remain open?

**Comment by ibusko** [comment]
Maybe should be a documentation issue? It isn't directly related to the code, but to the running environment, if I understand correctly.

**Comment by hcferguson** [comment]
I think this is addressed by #410 which is still pending. What's blocking it @ibusko

**Comment by ibusko** [comment]
@hcferguson yes, it is addressed by #410. Nothing is blocking it, except a code review.
