### ISSUE TITLE
UnitChange dialog doesn't handle no units case

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#452]
The unit change dialog will crash if there are no unit equivalencies. This might be the case if no units were parsed by the data (and therefore the plots units are `None`).

**Comment by javerbukh** [comment]
It seems the functionality is pretty much non-existent with current SpecViz. When trying to load HST/COS data `combined_13330_G130M_v40_bin4.fits` I get the error:
```ERROR:root:'CompositeUnit' object has no attribute 'long_names'
Traceback (most recent call last):
  File "/Users/javerbukh/Documents/specviz/specviz/core/plugin.py", line 209, in <lambda>
    action.triggered.connect(lambda: func(plugin, *args, **kwargs))
  File "/Users/javerbukh/Documents/specviz/specviz/plugins/unit_change/unit_change_dialog.py", line 135, in on_action_triggered
    self.exec_()
  File "/Users/javerbukh/Documents/specviz/specviz/plugins/unit_change/unit_change_dialog.py", line 128, in exec_
    self.setup_ui()
  File "/Users/javerbukh/Documents/specviz/specviz/plugins/unit_change/unit_change_dialog.py", line 149, in setup_ui
    index = self._data_unit_equivalencies_titles.index(self.current_data_unit)
ValueError: 'Joule' is not in list
Abort trap: 6```
I will remove references to 'long_names' as this seems to give problems after every SpecViz update

**Comment by gderosa2004** [comment]
Me and @nluetzge have played a bit with the unit change.
Here is what we have found when using example_generic.fits:

- Conversion of X is currently applied only to errors (not to flux)
![screen shot 2018-10-24 at 12 01 10 pm](https://user-images.githubusercontent.com/15363065/47446433-3b4a0c00-d789-11e8-85af-941e8305ea70.png)

- After one conversion is applied it is impossible to change units again (either X or Y), even if instance spectrum is deleted
![screen shot 2018-10-24 at 12 01 58 pm](https://user-images.githubusercontent.com/15363065/47446504-63396f80-d789-11e8-857b-1c7b1e5bfb5c.png)

- Specviz crashes if conversion not allowed

**Comment by javerbukh** [comment]
Test once #480 is merged.
