### ISSUE TITLE
Problems using example_generic.fits

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#524]
The file we have in there for example_generic.fits seems a bit strange in that it just has flux and error columns, no wavelength. 

That aside, specviz crashes on me as soon as I try to set a region. Error log below.

```
(specviz) ~/d/specviz_sprint_oct18 ❯❯❯ specviz                                ⏎
objc[61798]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffaf1fac90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c2a0ddcd8). One of the two will be used. Which one is undefined.
WARNING: FITSFixedWarning: The WCS transformation has more axes (1) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: The WCS transformation has more axes (1) than the image it is associated with (0)
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda3/envs/specviz/lib/python3.6/site-packages/specviz-0.6.dev1635-py3.6.egg/specviz/plugins/statistics/statistics_widget.py", line 255, in update_statistics
    self.stats = compute_stats(spec)
  File "/Users/hcferguson/anaconda3/envs/specviz/lib/python3.6/site-packages/specviz-0.6.dev1635-py3.6.egg/specviz/plugins/statistics/statistics_widget.py", line 60, in compute_stats
    flux = spectrum.flux
AttributeError: 'NoneType' object has no attribute 'flux'
[1]    61798 abort      specviz
(specviz) ~/d/specviz_sprint_oct18 ❯❯❯ specviz --version                               ⏎
0.6.dev01635
```

**Comment by nluetzge** [comment]
@hcferguson this is addressed in #471

**Comment by nluetzge** [comment]
See second comment.

**Comment by hcferguson** [comment]
Closing this issue. I don't think the example_generic.fits file is representative formats we would find with real data.
