### ISSUE TITLE
index not valid when deleting spectra

### ISSUE THREAD

**Issue by SaOgaz** [spacetelescope/specviz#592]
I'm getting an `Index not valid -1` printout in the terminal when I delete spectra data.  Right now I'm using files that open up many spectra into Specviz. It also completely crashes at times but I'm trying to replicated the crashes.

**Comment by SaOgaz** [comment]
Crash happens when I try and delete the first spectra in the list:

`
specviz [INFO    ]: Adding plot jw84600042001_02101_00001_nrs2_x1dints_ref-0

specviz [INFO    ]: Adding plot jw84600042001_02101_00001_nrs2_x1dints_ref-1

specviz [INFO    ]: Adding plot jw84600042001_02101_00001_nrs2_x1dints_ref-2

Index not valid -1
Index not valid -1
Traceback (most recent call last):
  File "/Users/ogaz/specviz/specviz/plugins/model_editor/model_editor.py", line 322, in _redraw_model
    model_plot_data_item = self.hub.plot_item
  File "/Users/ogaz/specviz/specviz/core/hub.py", line 47, in plot_item
    return self.workspace.current_item
AttributeError: 'Workspace' object has no attribute 'current_item'
Abort trap: 6
`
