### ISSUE TITLE
Model creation crashes when there are multiple ROI

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/specviz#604]
Working with stis1.ecsv, I defined 4 ROIs then tried to create a 2nd-order polynomial model. SpecViz crashed with the following traceback.

```
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda3/envs/specutils_dev/lib/python3.6/site-packages/specviz-0.6.dev1898-py3.6.egg/specviz/plugins/model_editor/model_editor.py", line 68, in <lambda>
    action.triggered.connect(lambda x, m=v: self._add_fittable_model(m))
  File "/Users/hcferguson/anaconda3/envs/specutils_dev/lib/python3.6/site-packages/specviz-0.6.dev1898-py3.6.egg/specviz/plugins/model_editor/model_editor.py", line 263, in _add_fittable_model
    model = initialize(model, spec.spectral_axis, spec.flux)
AttributeError: 'list' object has no attribute 'spectral_axis'
[1]    97936 abort      specviz
```

**Comment by nluetzge** [comment]
I get the same crash when I select a model and no data is selected.
