### ISSUE TITLE
Specviz crashes when loading an inappropriate data file

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/specviz#618]
I accidentally just tried to load a JWST IFU data file and specviz crashed with the following:

```
specviz [INFO    ]: Spectrum file looks like wcs1d-fits
specviz [WARNING ]: Attempted load with 'wcs1d-fits' failed, trying next loader.
Traceback (most recent call last):
  File "/Users/ddavella/specviz/specviz/widgets/plotting.py", line 351, in _check_unit_compatibility
    plot_data_item = self.proxy_model.item_from_id(item.identifier)
  File "/Users/ddavella/specviz/specviz/core/models.py", line 133, in item_from_id
    self._items[data_item.identifier] = PlotDataItem(data_item)
  File "/Users/ddavella/specviz/specviz/core/items.py", line 75, in __init__
    self._spectral_axis_unit = self._data_item.spectral_axis.unit.to_string()
  File "/Users/ddavella/specviz/specviz/core/items.py", line 46, in spectral_axis
    return self.data(self.DataRole).spectral_axis
  File "/Users/ddavella/miniconda3/envs/specutils/lib/python3.7/site-packages/astropy/utils/decorators.py", line 726, in __get__
    val = self.fget(obj)
  File "/Users/ddavella/specutils/specutils/spectra/spectrum_mixin.py", line 63, in spectral_axis
    spectral_axis = self.wcs.pixel_to_world(np.arange(self.flux.shape[-1]))
AttributeError: 'NoneType' object has no attribute 'pixel_to_world'
```

This is probably actually a problem in the `specutils` loader, but it should be handled gracefully on this end.

**Comment by nmearl** [comment]
Hmm, it looks like the only way this might have been caught is if the entire application instance had a try/except block. This is raised when specviz tried to access the `spectral_axis` on the `Spectrum1D` object, which could happen _anywhere_ in the application. But yeah, it's fundamentally as issue with `Spectrum1D`.

**Comment by brechmos-stsci** [comment]
From a specutils / specviz point of view, I tried loading `jw10001001001_01101_00001_mirifushort_s3d_ref.fits` with all of the loaders and they all fail "gracefully" except the `APOGEE apVisit` loader, so it is the one that seems to be the problem, so I'll take a look at it.
