### ISSUE TITLE
Problem with testing the last release in Python 3.9

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#706]
Requirement conflict with `mosviz`, see spacetelescope/mosviz#234

Also see spacetelescope/cubeviz#598 though the traceback here is a bit different:

```
Traceback (most recent call last):
  File ".../bin/specviz", line 5, in <module>
    from specviz.app import start
  File ".../specviz/__init__.py", line 25, in <module>
    import pyqtgraph as pg
  File ".../pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtGui
  File ".../pyqtgraph/Qt.py", line 153, in <module>
    from PyQt5 import QtGui, QtCore, QtWidgets, uic
ModuleNotFoundError: No module named 'sip'
```

**Comment by pllim** [comment]
In a clean environment without the other viz, I get a different error. Still no splash screen.

```
$ conda create -n <envname> python=3.9 qt
$ pip install specviz
$ specviz
Traceback (most recent call last):
  File ".../bin/specviz", line 5, in <module>
    from specviz.app import start
  File ".../specviz/__init__.py", line 75, in <module>
    load_settings()
  File ".../specviz/__init__.py", line 73, in load_settings
    pg.setConfigOptions(**pyqtgraph_settings)
  File ".../pyqtgraph/__init__.py", line 77, in setConfigOptions
    setConfigOption(k, v)
  File ".../pyqtgraph/__init__.py", line 66, in setConfigOption
    raise KeyError('Unknown configuration option "%s"' % opt)
KeyError: 'Unknown configuration option "useWeave"'
```

**Comment by pllim** [comment]
In clean environment with Python 3.6, the splash screen shows.

**Comment by ibusko** [comment]
The original JIRA ticket is JDAT-1296.

**Comment by eteq** [comment]
In some out-of-band discussion, I think we settled on the following solution:

* Set the  maximum python version to whatever we know works right now (which I think is 3.6?)
* This has the downside that anyone who pip installs will get a downgrade
* ASAP, we put out a last version that has *none* of the current dependencies (and therefore leads to no downgrades), but just creates the error on import that says "go to jdaviz"
